// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Nikolai Mazein",
            "email": "feynmaz@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/get/{code}": {
            "get": {
                "summary": "Получить ответ.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Код ответа",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success"
                    },
                    "400": {
                        "description": "error"
                    },
                    "401": {
                        "description": "error"
                    },
                    "403": {
                        "description": "error"
                    },
                    "404": {
                        "description": "error"
                    },
                    "429": {
                        "description": "error"
                    },
                    "500": {
                        "description": "error"
                    },
                    "503": {
                        "description": "error"
                    }
                }
            }
        }
    },
    "x-servers": [
        {
            "description": "dev",
            "url": "https://promfeeder.testshift.webtm.ru/"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Promfeeder API",
	Description:      "This is a service which feeds prometheus with metrics.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
